[package]
name = "svalin_sysctl"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
portable-pty = "0.9.0"
serde = { version = "1.0.219", features = ["derive"] }
sysinfo = { version = "0.34.2", features = ["windows", "serde"] }
tokio = { version = "1.44.2", features = ["sync"] }
