[package]
name = "frostbyte_term"
version = "0.1.0"
edition = "2024"

[dependencies]
frozen_term = { path = "../frozen_term" }
iced = { version = "0.13.1", features = ["tokio"] }
portable-pty = "0.9.0"
tokio = "1.43.1"
